// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGFW05xrMDKBY-sh_nSu2vepfb-cXmhBI',
    appId: '1:136395129148:web:7539e5c9f4b1cb22271e39',
    messagingSenderId: '136395129148',
    projectId: 'airbnb-clone-50715',
    authDomain: 'airbnb-clone-50715.firebaseapp.com',
    storageBucket: 'airbnb-clone-50715.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCccBodKRH5e29VGEFVTSMy2ZIRW2U-950',
    appId: '1:136395129148:android:814ea14222095e80271e39',
    messagingSenderId: '136395129148',
    projectId: 'airbnb-clone-50715',
    storageBucket: 'airbnb-clone-50715.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3HCH1b_TG7Iy3Ik78iDj2IexZ4LvI7OM',
    appId: '1:136395129148:ios:4005f6e6b2601fac271e39',
    messagingSenderId: '136395129148',
    projectId: 'airbnb-clone-50715',
    storageBucket: 'airbnb-clone-50715.appspot.com',
    iosClientId: '136395129148-cicjlgq4mtnce05gv9urdi3g0ts11khp.apps.googleusercontent.com',
    iosBundleId: 'com.airbnb-clone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3HCH1b_TG7Iy3Ik78iDj2IexZ4LvI7OM',
    appId: '1:136395129148:ios:41d8900aa18e6d2d271e39',
    messagingSenderId: '136395129148',
    projectId: 'airbnb-clone-50715',
    storageBucket: 'airbnb-clone-50715.appspot.com',
    iosClientId: '136395129148-m2q63mbamfddvijd1iek4j72ml524j9a.apps.googleusercontent.com',
    iosBundleId: 'com.example.airbnbClone',
  );
}
